name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'  # atualiza todo dia
  workflow_dispatch:

jobs:
  update-readme:
    name: Atualiza o WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_3d1249dd-2480-47a4-82ed-e3a207866cb7 }}
          SHOW_TITLE: true
          COMMIT_MESSAGE: "Atualizando estatísticas do WakaTime ⏱"
